# Generated by Django 6.0.1 on 2026-01-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postingitem',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
